language: cpp
sudo: true
script: cmake
cache:
  apt: true
  directories:
  - ${TRAVIS_BUILD_DIR}/deps/protobuf

env:
  global:
    - BOOST_VERSION="1.69.0"
    - PROTOBUF_VERSION="3.6.1"
    - CMAKE_VERSION="3.13.2"
    - RC_PARAMS="verbose_progress=1 verbose_shrinking=1"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-7
    packages:
    - build-essential
    - clang-7
    - libc++-7-dev
    - libc++abi-7-dev
matrix:
  include:
  - os: linux
    env: COMPILER='clang++-7' BUILD_TYPE='Release'
  - os: linux
    env: COMPILER='clang++-7' BUILD_TYPE='Debug'
  - os: osx
    env: COMPILER='clang++' BUILD_TYPE='Release'
  - os: osx
    env: COMPILER='clang++' BUILD_TYPE='Debug'

install:
- |
  mkdir -p "${TRAVIS_BUILD_DIR}/deps" && cd $_
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    mkdir -p boost && cd $_
    BOOST_URL="https://dl.bintray.com/boostorg/release/${BOOST_VERSION}/source/boost_${BOOST_VERSION//./_}.tar.gz"
    travis_retry wget --no-check-certificate --quiet -O - "${BOOST_URL}" | tar --strip-components=1 -xz
    sudo cp -r boost /usr/include
    cd ..

    mkdir -p cmake && cd $_
    CMAKE_URL="https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz"
    travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz
    export PATH="$(pwd)/bin:${PATH}"
    cd ..

    mkdir -p "protobuf/${PROTOBUF_VERSION}" && cd $_
    PROTOBUF_URL="https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOBUF_VERSION}/protobuf-all-${PROTOBUF_VERSION}.tar.gz"
    travis_retry wget --no-check-certificate --quiet -O - "${PROTOBUF_URL}" | tar --strip-components=1 -xz
    cmake ./cmake -DCMAKE_POSITION_INDEPENDENT_CODE=ON -Dprotobuf_BUILD_SHARED_LIBS=ON -DCMAKE_EXE_LINKER_FLAGS="-stdlib=libc++ -lc++abi" -DCMAKE_CXX_COMPILER=clang++
    make -j"$(nproc)"
    make check
    sudo make install
    sudo ldconfig
    cd ../..
  elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
    brew upgrade cmake || brew install cmake
    brew upgrade boost || brew install boost
    brew upgrade protobuf || brew install protobuf
    brew upgrade llvm || brew install llvm --with-clang
    export PATH="/usr/local/opt/llvm/bin:$PATH"
    export LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"
  fi

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - ${COMPILER} --version
  - cmake . -DCMAKE_CXX_COMPILER=${COMPILER} -DCONFIG=${BUILD_TYPE} -DUSE_LIBCXX=ON -DFORMAT_FILES_WITH_CLANG_FORMAT_BEFORE_EACH_BUILD=OFF -DCLANG_TIDY_ENABLE=OFF

script:
- make -j"$(nproc)"
- ctest -VV
