language: cpp
sudo: true
script: cmake
dist: xenial

services:
  - docker

env:
  global:
    - RC_PARAMS="verbose_progress=1 verbose_shrinking=1 max_discard_ratio=100"

matrix:
  include:
  - os: linux
    env: COMPILER='clang++' BUILD_TYPE='Release'
  - os: linux
    env: COMPILER='clang++' BUILD_TYPE='Debug'
  - os: osx
    env: COMPILER='clang++' BUILD_TYPE='Release'
  - os: osx
    env: COMPILER='clang++' BUILD_TYPE='Debug'

install:
- cd ${TRAVIS_BUILD_DIR}
- source ci/scripts/${TRAVIS_OS_NAME}/install.sh

script:
- ${COMPILER} --version
- source ci/scripts/${TRAVIS_OS_NAME}/script.sh

after_success:
- source ci/scripts/${TRAVIS_OS_NAME}/after_success.sh

before_deploy:
- cd $TRAVIS_BUILD_DIR
- sed -e "s/@VERSION@/$(./version.sh)/g" ci/bintray.in > bintray.json

deploy:
- provider: bintray
  file: "bintray.json"
  user: "coord-e"
  key: $BINTRAY_API_KEY
  skip_cleanup: true
  on:
    condition: "$BUILD_TYPE = Release"
    all_branches: true
- provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  skip_cleanup: true
  file_glob: true
  file: 'build/dist/*'
  on:
    condition: "$BUILD_TYPE = Release"
    tags: true
