language: cpp
sudo: true
script: cmake
dist: xenial
cache:
  apt: true
services:
  - docker

env:
  global:
    - BOOST_VERSION="1.69.0"
    - PROTOBUF_VERSION="3.6.1"
    - CMAKE_VERSION="3.13.2"
    - RC_PARAMS="verbose_progress=1 verbose_shrinking=1"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-xenial-7
    packages:
    - build-essential
    - clang-7
    - libc++-7-dev
    - libc++abi-7-dev
matrix:
  include:
  - os: linux
    env: COMPILER='clang++-7' BUILD_TYPE='Release'
  - os: linux
    env: COMPILER='clang++-7' BUILD_TYPE='Debug'
  - os: osx
    env: COMPILER='clang++' BUILD_TYPE='Release'
  - os: osx
    env: COMPILER='clang++' BUILD_TYPE='Debug'

install:
- |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    docker build test-image/ -t test
  elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
    brew upgrade cmake || brew install cmake
    brew upgrade boost || brew install boost
    brew upgrade protobuf || brew install protobuf
    brew upgrade llvm || brew install llvm --with-clang
    export PATH="/usr/local/opt/llvm/bin:$PATH"
    export LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"
  fi

script:
- |
  cd ${TRAVIS_BUILD_DIR}
  ${COMPILER} --version
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    docker run --rm -v $(pwd):/source test
  elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
    cmake . -DCMAKE_CXX_COMPILER=${COMPILER} -DCONFIG=${BUILD_TYPE} -DUSE_LIBCXX=ON -DFORMAT_FILES_WITH_CLANG_FORMAT_BEFORE_EACH_BUILD=OFF -DCLANG_TIDY_ENABLE=OFF
    make -j"$(nproc)"
    ctest -VV
  fi
