language: cpp
sudo: true
script: cmake
cache:
  apt: true
  ccache: true
  directories:
  - ${TRAVIS_BUILD_DIR}/deps/protobuf

env:
  global:
    - BOOST_VERSION="1.69.0"
    - PROTOBUF_VERSION="3.6.1"
    - CMAKE_VERSION="3.13.2"
    - RC_PARAMS="verbose_progress=1 verbose_shrinking=1"
    - USE_CCACHE=1
    - CCACHE_DIR="${HOME}/.ccache"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-7
    packages:
    - build-essential
    - clang-7
    - libc++-7-dev
    - libc++abi-7-dev
matrix:
  include:
  - os: linux
    env: COMPILER='clang++-7' BUILD_TYPE='Release'
  - os: linux
    env: COMPILER='clang++-7' BUILD_TYPE='Debug'
  - os: osx
    env: COMPILER='clang++' BUILD_TYPE='Release'
  - os: osx
    env: COMPILER='clang++' BUILD_TYPE='Debug'

install:
- |
  mkdir "${TRAVIS_BUILD_DIR}/deps" && cd $_
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    mkdir boost && cd $_
    BOOST_URL="https://dl.bintray.com/boostorg/release/${BOOST_VERSION}/source/boost_${BOOST_VERSION//./_}.tar.gz"
    travis_retry wget --no-check-certificate --quiet -O - "${BOOST_URL}" | tar --strip-components=1 -xz
    ./bootstrap.sh
    sudo ./b2 headers
    cd ..

    mkdir cmake && cd $_
    CMAKE_URL="https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz"
    travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz
    export PATH="$(pwd)/bin:${PATH}"
    cd ..

    mkdir "protobuf/${PROTOBUF_VERSION}" && cd $_
    PROTOBUF_URL="https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOBUF_VERSION}/protobuf-cpp-${PROTOBUF_VERSION}.tar.gz"
    travis_retry wget --no-check-certificate --quiet -O - "${PROTOBUF_URL}" | tar --strip-components=1 -xz
    ./configure
    make -j"$(nproc)"
    make check
    sudo make install
    sudo ldconfig
    cd ../..
  elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
    brew list cmake &> /dev/null || brew install cmake
    brew list boost &> /dev/null || brew install boost
    brew list protobuf &> /dev/null || brew install protobuf
    brew list llvm &> /dev/null || brew install llvm --with-clang
    brew list ccache &> /dev/null || brew install ccache
    export PATH="/usr/local/opt/ccache/libexec:$PATH"
  fi

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - ${COMPILER} --version
  - cmake . -DFORMAT_BEFORE_BUILD=OFF -DCMAKE_CXX_COMPILER="ccache ${COMPILER}" -DCONFIG=${BUILD_TYPE} -DUSE_LIBCXX=ON

script:
- make -j"$(nproc)"
- ctest -VV
