language: cpp
sudo: true
script: cmake
dist: xenial

cache:
  directories:
    - $HOME/Library/Caches/Homebrew

services:
  - docker

env:
  global:
    - RC_PARAMS="verbose_progress=1 verbose_shrinking=1 max_discard_ratio=100"

matrix:
  include:
  - os: linux
    env: COMPILER='clang++' BUILD_TYPE='Release'
  - os: linux
    env: COMPILER='clang++' BUILD_TYPE='Debug' PACKAGE=false
  - os: osx
    env: COMPILER='clang++' BUILD_TYPE='Release'
  - os: osx
    env: COMPILER='clang++' BUILD_TYPE='Debug' PACKAGE=false
  - os: linux
    env: CROSS=-cross BASE_IMAGE=raspberry-pi DEBIAN_VERSION=stretch COMPILER='clang++-4.0' BUILD_TYPE='Release' ENABLE_TEST=OFF
  - os: linux
    env: CROSS=-cross BASE_IMAGE=raspberrypi3 DEBIAN_VERSION=stretch COMPILER='clang++-4.0' BUILD_TYPE='Release' ENABLE_TEST=OFF

before_cache:
- |
  if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
    brew cleanup
  fi

install:
- cd ${TRAVIS_BUILD_DIR}
- source ci/scripts/${TRAVIS_OS_NAME}${CROSS}/install.sh

script:
- cd ${TRAVIS_BUILD_DIR}
- source ci/scripts/${TRAVIS_OS_NAME}${CROSS}/script.sh

after_success:
- cd ${TRAVIS_BUILD_DIR}
- source ci/scripts/${TRAVIS_OS_NAME}${CROSS}/after_success.sh

before_deploy:
- cd ${TRAVIS_BUILD_DIR}
- sed -e "s/@VERSION@/$(./version.sh)/g" ci/bintray.in > bintray.json

deploy:
- provider: bintray
  file: "bintray.json"
  user: "coord-e"
  key: $BINTRAY_API_KEY
  skip_cleanup: true
  on:
    condition: "$BUILD_TYPE = Release"
    all_branches: true
- provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  skip_cleanup: true
  file_glob: true
  file: 'build/dist/*'
  on:
    condition: "$BUILD_TYPE = Release"
    tags: true
